#SPDX-FileCopyrightText: Copyright (c) 2021 Sidings Media 
#
#SPDX-License-Identifier: CC0-1.0

version: 2

sphinx:
  builder: html
  configuration: ./conf.py

formats:
    - pdf
    - htmlzip
    - epub

python:
  version: "3.8"
  install:
    - requirements: ./requirements.txt
    - method: pip
